# Generated by Django 4.1.6 on 2023-02-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('alcohol_id', models.AutoField(primary_key=True, serialize=False)),
                ('alcohol_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=50)),
                ('tool_image', models.ImageField(upload_to='static/media/tools')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_image1', models.ImageField(upload_to='static/media/recipes')),
                ('recipe_image2', models.ImageField(upload_to='static/media/recipes')),
                ('recipe_title', models.CharField(max_length=50)),
                ('recipe_description', models.TextField(max_length=1000)),
                ('recipe_ingredients', models.CharField(max_length=50)),
                ('recipe_steps', models.CharField(max_length=50)),
                ('recipe_alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alcohol')),
                ('recipe_tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50)),
                ('food_image1', models.ImageField(upload_to='static/media/food')),
                ('food_image2', models.ImageField(upload_to='static/media/food')),
                ('food_title', models.CharField(max_length=50)),
                ('food_description', models.TextField(max_length=1000)),
                ('food_ingredients', models.CharField(max_length=50)),
                ('food_steps', models.CharField(max_length=50)),
                ('food_alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recipe')),
            ],
        ),
    ]
