# Generated by Django 4.1.6 on 2023-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_food_food_ingredients_alter_food_food_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_alcohol',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_alcohol',
            field=models.ManyToManyField(to='home.alcohol'),
        ),
    ]
