# Generated by Django 4.1.6 on 2023-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_recipe_recipe_alcohol_recipe_recipe_alcohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_tools',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_tools',
            field=models.ManyToManyField(to='home.tool'),
        ),
    ]
