# Generated by Django 4.1.6 on 2023-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_recipe_recipe_tools_recipe_recipe_tools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='recipe_description1',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_description2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
