# Generated by Django 4.1.6 on 2023-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_recipe_description_recipe_recipe_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ManyToManyField(to='home.type'),
        ),
    ]
