# Generated by Django 4.1.6 on 2023-03-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_type_food_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('article_photo', models.ImageField(upload_to='article_photos')),
                ('article_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='article_field_photos')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='home.article')),
            ],
            options={
                'unique_together': {('article', 'id')},
            },
        ),
    ]
