# Generated by Django 4.1.6 on 2023-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_article_articlefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=100)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('book_image_1_1', models.ImageField(upload_to='static/media/book')),
                ('book_image_1_2', models.ImageField(upload_to='static/media/book')),
                ('book_image_1_3', models.ImageField(upload_to='static/media/book')),
                ('book_description_1', models.TextField(max_length=1000)),
                ('book_image_2_1', models.ImageField(upload_to='static/media/book')),
                ('book_image_2_2', models.ImageField(upload_to='static/media/book')),
                ('book_image_2_3', models.ImageField(upload_to='static/media/book')),
                ('book_description_2', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articlefield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articlefield',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleField',
        ),
    ]
