# Generated by Django 4.1.4 on 2023-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_book_alter_articlefield_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("video_url", models.CharField(max_length=255)),
                ("video_title", models.CharField(max_length=200)),
            ],
        ),
    ]
