# Generated by Django 4.1.4 on 2023-03-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_article_articlesection"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlesection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="articlesection",
            name="article",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="ArticleSection",
        ),
    ]
