# Generated by Django 4.1.4 on 2023-03-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_article_articlesection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesection",
            name="article",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="ArticleSection",
        ),
    ]
