# Generated by Django 4.1.4 on 2023-03-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_remove_articlesection_article_delete_article_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("article_title", models.CharField(max_length=255)),
                ("article_image", models.ImageField(upload_to="static/media/article")),
            ],
        ),
        migrations.CreateModel(
            name="ArticleSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.CharField(max_length=255)),
                ("section_image", models.ImageField(upload_to="static/media/article")),
                ("section_description", models.TextField(max_length=1000)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.article"
                    ),
                ),
            ],
        ),
    ]
