# Generated by Django 4.1.4 on 2023-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_article_articlesection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesection",
            name="section_description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="articlesection",
            name="section_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/media/article"
            ),
        ),
        migrations.AlterField(
            model_name="articlesection",
            name="section_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
