# Generated by Django 4.1.4 on 2023-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_articlesection_section_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_alcohol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_type",
            field=models.ManyToManyField(blank=True, null=True, to="home.type"),
        ),
    ]
