# Generated by Django 4.1.4 on 2023-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_food_food_alcohol_alter_food_food_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                ("subscribe_id", models.AutoField(primary_key=True, serialize=False)),
                ("subscribe_email", models.CharField(max_length=254)),
                ("subscribe_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
